### ISSUE TITLE
Some videos are not embedded properly/at all

### ISSUE THREAD

**Issue by Kyrela** [iGerman00/koutube#12]
Maybe these should be separate issues.

Example of a video that does not embed at all:
https://www.youtube.com/watch?v=9eVYSJqso7w
This may be due to its length.

Example of a video that embeds only description, stats, and info (no video)
https://www.youtube.com/watch?v=9eVYSJqso7w
Might be related to the fact that it's music - I don't even know if it's considered a video by youtube - but it definitely plays as a video in browsers.

**Comment by iGerman00** [comment]
This is not fixable by Koutube.

Long videos will not embed on Discord due to the size, but they do actually work fine - you can check the response by running `curl https://www.youtube.com/watch?v=9eVYSJqso7w` in a terminal

As for those cases with all the info and no video, that happens when the video is unavailable for any reasons, such as Invidious being blocked by YouTube again, age restriction, or copyright/embed restrictions.
