### ISSUE TITLE
Start at current time video

### ISSUE THREAD

**Issue by RoyRiv3r** [iGerman00/koutube#5]
Is that possible to set current time and start at that time of the video? 
https://youtu.be/Z8WKR0VHfJw?t=285

**Comment by iGerman00** [comment]
It's not and unfortunately it doesn't seem like it's possible without a lot of server time

**Comment by RoyRiv3r** [comment]
Does this provider help for the time perhaps or is it related to discord? https://inv.tux.pizza/watch?v=BH45hWntkq4&t=150

**Comment by iGerman00** [comment]
It's due to the fact that the native discord (or any other like telegram) player just plays the video you give it, there's no control over when it starts apart from processing the video to only start at `t`, which is very computationally expensive as I'd have to re-encode it before passing it to the client

**Comment by RoyRiv3r** [comment]
I see that's unfortunate, thanks for clarification!
